brew "git"
brew "tig"
brew "fzf"
brew "neovim"
brew "man-db"
brew "neofetch"
brew "htop"

# shell
brew "fish"
brew "fisher"
brew "eza"

# tmux stuff
brew "tmux"
brew "tmuxp"
brew "tpm"

# container garbage
brew "devcontainer"
