#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[ui]
default-command = "status"
describe-show-full-diff = true

[aliases]
g = ["git"]
tug = ["bookmark", "advance"]
fetch = ["git", "fetch"]
f = ["git", "fetch"]
push = ["git", "push"]
p = ["git", "push"]
fetch-pr = ['util', 'exec', '--', 'jj-fetch-pr']
pr = ["fetch-pr"]


[user]
name = "Chris Pickard"
email = "chris.pickard@tangramflex.com"

[git]
private-commits = '''description('XXX:*')'''
