#! /bin/bash

WINTITLE=$1 # Main Thunderbird window has this in titlebar

# Use wmctrl to list all windows, count how many contain WINTITLE,
# and test if that count is non-zero:

if [ `wmctrl -l | grep -c "$WINTITLE"` != 0 ]
then
    wmctrl -c "$WINTITLE" # If it exists, bring t-bird window to front
fi
exit 0
