#!/usr/bin/env sh

set -e
set -o pipefail

BRANCH=$(jira jsonmine \
            | jq -r ".issues[] | {id: .key, summary: .fields.summary} | join(\" \")" \
            | sed -e 's/ /_/g' | fzf -1 +m -q "$1" | cut -c -75)
ORG_FILE="$BRANCH.org"
cat > "$ORG_FILE" <<EOF
#+OPTIONS: ^:nil
* Test Steps
** Prerequisites
** Test Steps
EOF

$EDITOR "$ORG_FILE"
