#!/usr/bin/env bash

branches=$(git branch --all | grep -v HEAD) &&
    branch=$(echo "$branches" |
                 fzf-tmux -d $(( 2 + $(wc -l <<< "$branches") )) -q "$1" +m) &&
    git checkout $(echo "$branch" | sed "s/.* //" | sed "s#remotes/[^/]*/##")
